# compose/helix-llm/llm-stack.yml
# -------------------------------------------------------------
# 🧠 HELIXNET LLM STACK 💦️ compose/helix-llm/llm-stack.yml 
# ☕️ Clean Production Edition — OLLAMA + OPENWEBUI + QDRANT
# -------------------------------------------------------------
services:
# -------------------------------------------------------------
# 🧠 LLM ollama 
# -------------------------------------------------------------
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks: [ helixnet_core ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/app/ollama-data     # FIX: Paths made relative to the project root (../../)
      - ../../data/ollama/config:/config
      - ../../data/ollama/models:/data/models
      - ../../data/ollama/cache:/root/.ollama
    healthcheck:
      # TWEAK: Using the 'ollama list' command for a more comprehensive health check
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
# -------------------------------------------------------------
# 🐿️ Wb Ui openwebui
# -------------------------------------------------------------
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY:-helix_pass}
      OLLAMA_API_BASE: http://ollama:11434
    ports:
      - "3001:8080"
    networks: [ helixnet_core ]
    volumes:
      - openwebui_data:/app/openwebui-data      # FIX: Path made relative to the project root (../../)
      - ../../data/openwebui:/app/backend/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
# -------------------------------------------------------------
# 🐿️ Vector Db qdrant
# # # -------------------------------------------------------------
#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant
#     restart: unless-stopped
#     networks: [ helixnet_core ]
#     ports:
#       - "6333:6333"
#     volumes:
#       - qdrant_data:/app/qdrant-data      # FIX: Path made relative to the project root (../../)
#       - ../../data/qdrant:/qdrant/storage
#     environment:
#       QDRANT__SERVICE__GRPC_PORT: "6334"
#       QDRANT__STORAGE__PATH: "/qdrant/storage"
#     healthcheck:
#       # TWEAK: Standard HTTP health check endpoint
#       test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
#       interval: 10s
#       timeout: 5s
#       retries: 20
#       start_period: 20s
#   # doc-processor:
  #   build: ./doc-processor
  #   environment:
  #     - QDRANT_URL=qdrant:6333
# # -------------------------------------------------------------
# # 🐿️ LLM Debugger debLLM
# # -> This block was moved from the 'volumes' section.
# # # -------------------------------------------------------------
#   debllm:
#     build:
#       context: ../../
#       dockerfile: compose/helix-llm/Dockerfile.debLLM
#     container_name: debllm
#     restart: always
#     env_file:
#       - ../../env/helix.env
#     volumes:
#       - ../../src:/app/src
#       - debllm_data:/app/debllm-data      
#     environment:
#       - OLLAMA_URL=http://ollama:11434
#       # Note: QDRANT is commented out, so you might need to comment out this URL too, or uncomment QDRANT service.
#       - QDRANT_URL=http://qdrant:6333
#       - POSTGRES_DSN=postgresql://helix_user:helix_pass@postgres:5432/helix_db
#       - OLLAMA_MODEL=tinyllama:latest
#     networks: [ helixnet_core ]
#     ports:
#       - "5001:5001"
#     depends_on:
#       ollama:
#         condition: service_started
#       qdrant:
#         condition: service_started

# # -------------------------------------------------------------
# 🗂️ NAMED VOLUMES (Define the volume names here)
# -------------------------------------------------------------
volumes:
  ollama_data:
  openwebui_data:
 
  debllm_data:
  qdrant_data:
# -------------------------------------------------------------
# 🌐 Networks (The networks section is fine as you defined it)
# -------------------------------------------------------------
networks:
  helixnet_core:
    external: true
  helixnet_edge:
    external: true