FROM helix-platform:latest

WORKDIR /app
COPY src /app/src

CMD ["python", "-m", "celery", "-A", "src.tasks.celery_app:app", "beat", "--loglevel=INFO", "--schedule", "/app/beat-data/celerybeat.schedule"]
