#!/usr/bin/env python3
"""word_to_3d.py -- the grand recipe (bench tool): a WORD -> a 3D-printable STL, stamped + authentic.

Angel's spec (2026-06-12):
- text in -> extruded, watertight, base-plated solid the 3D-printer guy can print in plain B&W.
- AUTHENTICITY STAMP engraved MIRRORED into the underside of the base: serial No + La Piazza +
  maker + date. Flip the piece over and it reads correct -> a provably authentic piece (Banksy serial,
  made physical). Extra metadata can be added later.
- FONTS are the variable: Bauhaus (URW Gothic), Bold (Liberation Sans), stencil/Banksy (coming).
- MULTI-VIEW previews (his "see all the views"): iso, top (readable), bottom (the stamp), side (depth).

Engine: OpenSCAD (text() + linear_extrude(), STL + PNGs from the CLI, no mouse). Zero-dependency
standalone (stdlib) so it runs on a bare laptop; this is the exact core the Bottega recipe will call
once OpenSCAD is in the container + binary (STL) serving is wired (a separate, deliberate block).

    sudo apt install openscad
    python scripts/word_to_3d.py FREEDOM --style bauhaus
Output -> ./dist/ : <word>.scad (source), <word>.stl (print this), <word>_{iso,top,bottom,side}.png.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

# Curated font presets -> fontconfig names that are actually installed on this box (verified via
# fc-list). "stencil" falls back to bold until we install a real stencil/Banksy face (one apt away).
FONTS = {
    "bauhaus":  "URW Gothic:style=Demi",        # geometric, round -- Angel's Bauhaus ask
    "bold":     "Liberation Sans:style=Bold",   # clean heavy sans
    "stencil":  "Liberation Sans:style=Bold",   # TODO: real stencil font (placeholder for now)
}
STAMP_FONT = "Liberation Sans:style=Bold"        # small underside text -> legibility over style

# Camera EYE-vectors (direction is what matters; --viewall reframes). Bottom view shows the stamp.
VIEWS = {
    "iso":    "140,-140,110,0,0,0",
    "top":    "0,0,180,0,0,0",      # straight down -> the word, readable
    "bottom": "0,0,-180,0,0,0",     # straight up   -> the engraved authenticity stamp
    "side":   "0,-180,0,0,0,0",     # edge-on       -> the depth / base profile
}

# OpenSCAD source. Tokens (__LIKE_THIS__) are string-replaced so we never fight literal { } braces.
SCAD_TEMPLATE = r"""// Generated by word_to_3d.py -- the grand recipe.
word        = __WORD__;
size        = __SIZE__;          // letter height
height      = __HEIGHT__;        // extrude depth (the 3D thickness)
font        = __FONT__;
base_h      = __BASE_H__;        // base plate thickness (carries the stamp, joins loose letters)
base_m      = __BASE_M__;        // margin of base around the text
stamp_lines = __STAMP_LINES__;   // engraved mirrored on the underside
stamp_font  = __STAMP_FONT__;
stamp_size  = __STAMP_SIZE__;
stamp_depth = __STAMP_DEPTH__;   // how deep the stamp is recessed into the base bottom
$fn = 48;

module text2d()  { text(word, size = size, font = font, halign = "center", valign = "center"); }
module base2d()  { hull() offset(r = base_m) text2d(); }   // solid convex plaque -> always stamp-able

module stamp2d() {
    n  = len(stamp_lines);
    lh = stamp_size * 1.5;
    for (i = [0 : n - 1])
        translate([0, (n - 1) / 2 * lh - i * lh, 0])
            text(stamp_lines[i], size = stamp_size, font = stamp_font,
                 halign = "center", valign = "center");
}

difference() {
    union() {
        linear_extrude(height = base_h) base2d();              // the plaque
        translate([0, 0, base_h]) linear_extrude(height = height) text2d();   // raised letters
    }
    // engrave the stamp into the UNDERSIDE; mirror so it reads correctly once the piece is flipped
    translate([0, 0, -0.01])
        linear_extrude(height = stamp_depth + 0.01)
            mirror([1, 0, 0]) stamp2d();
}
"""


def make_serial(word: str, maker: str, today: str) -> str:
    h = hashlib.sha1(f"{word}|{maker}|{today}".encode()).hexdigest()[:4].upper()
    return f"{today.replace('-', '')}-{h}"


def render(word: str, *, size: float, height: float, font: str, base_h: float, base_m: float,
           maker: str, stamp: bool, outdir: Path) -> int:
    outdir.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() else "_" for c in word).strip("_") or "word"
    scad = outdir / f"{safe}.scad"
    stl = outdir / f"{safe}.stl"

    today = datetime.date.today().isoformat()
    serial = make_serial(word, maker, today)
    stamp_lines = [f"LA PIAZZA #{serial}", f"by {maker} - {today}"] if stamp else []

    src = SCAD_TEMPLATE
    for tok, val in {
        "__WORD__": json.dumps(word), "__SIZE__": size, "__HEIGHT__": height,
        "__FONT__": json.dumps(font), "__BASE_H__": base_h, "__BASE_M__": base_m,
        "__STAMP_LINES__": json.dumps(stamp_lines), "__STAMP_FONT__": json.dumps(STAMP_FONT),
        "__STAMP_SIZE__": max(2.0, size * 0.16), "__STAMP_DEPTH__": 0.6,
    }.items():
        src = src.replace(tok, str(val))
    scad.write_text(src)
    print(f"  wrote {scad}   (serial {serial})")

    openscad = shutil.which("openscad")
    if not openscad:
        print("\n  OpenSCAD not installed -- .scad source is ready. Install + re-run:")
        print(f"      sudo apt install openscad && python {Path(__file__).name} {word!r}")
        return 2

    try:
        subprocess.run([openscad, "-o", str(stl), str(scad)],
                       check=True, capture_output=True, text=True)
        for name, cam in VIEWS.items():
            png = outdir / f"{safe}_{name}.png"
            subprocess.run([openscad, "-o", str(png), "--viewall", "--autocenter",
                            "--projection=ortho", f"--camera={cam}", "--imgsize=820,520", str(scad)],
                           check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"  OpenSCAD failed: {e.stderr or e}", file=sys.stderr)
        return 1

    print(f"  rendered {stl}  <- send this to the printer")
    print(f"  previews {outdir}/{safe}_(iso|top|bottom|side).png   (bottom = the authenticity stamp)")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Turn a WORD into a stamped, 3D-printable STL (+ previews).")
    p.add_argument("word", help="the word/phrase, e.g. FREEDOM")
    p.add_argument("--style", choices=sorted(FONTS), default="bauhaus", help="font preset (default bauhaus)")
    p.add_argument("--font", default="", help="raw fontconfig name; overrides --style")
    p.add_argument("--size", type=float, default=20.0, help="letter height (default 20)")
    p.add_argument("--height", type=float, default=5.0, help="extrude depth (default 5)")
    p.add_argument("--base", type=float, default=2.0, dest="base_h", help="base/plaque thickness (default 2)")
    p.add_argument("--margin", type=float, default=3.0, dest="base_m", help="base margin around text")
    p.add_argument("--maker", default="La Piazza", help="maker name for the stamp")
    p.add_argument("--no-stamp", action="store_false", dest="stamp", help="skip the authenticity stamp")
    p.add_argument("--out", type=Path, default=Path("dist"), help="output dir (default ./dist)")
    a = p.parse_args()
    font = a.font or FONTS[a.style]
    print(f"word_to_3d: making {a.word!r}  [{font}] ...")
    return render(a.word, size=a.size, height=a.height, font=font, base_h=a.base_h,
                  base_m=a.base_m, maker=a.maker, stamp=a.stamp, outdir=a.out)


if __name__ == "__main__":
    raise SystemExit(main())
