#!/usr/bin/env python3
"""word_to_3d.py -- the proof of concept: a WORD -> a 3D-printable STL (+ a preview PNG).

The grand recipe, smallest possible first step (Angel, 2026-06-12): take an inspirational word,
extrude it into a solid you can hand to a 3D-printer guy. Banksy-stencil words skip the hard part
(tracing an image) -- pure text extrudes clean. OpenSCAD is the engine: `text()` + `linear_extrude()`
turn a word into geometry, and it exports STL + PNG from the CLI with no mouse.

This is deliberately a zero-dependency standalone (stdlib argparse) so it runs on a bare laptop the
moment OpenSCAD is installed. When it graduates into a Bottega recipe it gets the Typer/Pydantic
treatment (CLAUDE.md rule 11); for the bench proof, this is enough.

Install the engine first (Debian):   sudo apt install openscad
Then:                                python scripts/word_to_3d.py FREEDOM
Output lands in ./dist/ : FREEDOM.scad (the source), FREEDOM.stl (print this), FREEDOM.png (preview).
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

# An OpenSCAD program, parameterised. Bold, centred, extruded text on an optional thin base plate
# (the base gives the print something to sit on and keeps loose letters joined). Everything here is
# a knob a recipe can expose later: the word, the font, how tall (extrude), how big (point size),
# and the base thickness/margin.
SCAD_TEMPLATE = """// Generated by word_to_3d.py -- the grand recipe, bench proof.
word    = {word};        // OpenSCAD strings are DOUBLE-quoted (JSON-encoded here)
size    = {size};        // letter height (mm-ish, OpenSCAD units)
height  = {height};      // how far we extrude UP (the 3D depth)
font    = {font};        // try "DejaVu Sans:style=Bold" or any installed bold font
base_h  = {base_h};      // base plate thickness (0 = letters only)
base_m  = {base_m};      // margin of base around the text
$fn     = 64;            // curve smoothness

module letters() {{
    linear_extrude(height = height)
        text(word, size = size, font = font, halign = "center", valign = "center");
}}

// the printable solid: base plate (if any) + raised letters
if (base_h > 0) {{
    // a base sized to the text bounds + margin, centred under the letters
    resize([0,0,0]) union() {{
        translate([0,0,0])
            linear_extrude(height = base_h)
                offset(r = base_m)
                    text(word, size = size, font = font, halign = "center", valign = "center");
        translate([0,0,base_h]) letters();
    }}
}} else {{
    letters();
}}
"""


def render(word: str, *, size: float, height: float, font: str,
           base_h: float, base_m: float, outdir: Path) -> int:
    outdir.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() else "_" for c in word).strip("_") or "word"
    scad = outdir / f"{safe}.scad"
    stl = outdir / f"{safe}.stl"
    png = outdir / f"{safe}.png"

    scad.write_text(SCAD_TEMPLATE.format(
        word=json.dumps(word), size=size, height=height, font=json.dumps(font),
        base_h=base_h, base_m=base_m))
    print(f"  wrote {scad}")

    openscad = shutil.which("openscad")
    if not openscad:
        print("\n  OpenSCAD is not installed yet -- the .scad source is ready, but I can't render the")
        print("  STL/PNG until the engine is here. Install it, then re-run:")
        print("      sudo apt install openscad")
        print(f"      python {Path(__file__).name} {word!r}")
        return 2

    # STL = the printable mesh; PNG = a preview you can eyeball before printing.
    try:
        subprocess.run([openscad, "-o", str(stl), str(scad)], check=True)
        subprocess.run([openscad, "-o", str(png), "--imgsize=900,600",
                        "--colorscheme=Tomorrow Night", str(scad)], check=True)
    except subprocess.CalledProcessError as e:
        print(f"  OpenSCAD failed: {e}", file=sys.stderr)
        return 1

    print(f"  rendered {stl}  <- send this to the printer")
    print(f"  preview  {png}  <- eyeball this first")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Turn a WORD into a 3D-printable STL (+ preview).")
    p.add_argument("word", help="the word to make, e.g. FREEDOM")
    p.add_argument("--size", type=float, default=20.0, help="letter height (default 20)")
    p.add_argument("--height", type=float, default=5.0, help="extrude depth / 3D thickness (default 5)")
    p.add_argument("--font", default="DejaVu Sans:style=Bold", help="bold font for the stencil look")
    p.add_argument("--base", type=float, default=1.5, dest="base_h",
                   help="base plate thickness, 0 for letters only (default 1.5)")
    p.add_argument("--margin", type=float, default=2.0, dest="base_m", help="base margin around text")
    p.add_argument("--out", type=Path, default=Path("dist"), help="output dir (default ./dist)")
    a = p.parse_args()
    print(f"word_to_3d: making {a.word!r} ...")
    return render(a.word, size=a.size, height=a.height, font=a.font,
                  base_h=a.base_h, base_m=a.base_m, outdir=a.out)


if __name__ == "__main__":
    raise SystemExit(main())
